// Auto-generated by tools/generate_eos_stubs.py. Do not edit manually.

#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <Windows.h>
#ifdef Options
#undef Options
#endif

#define EOS_BUILD_DLL 1

#include "eos_sdk.h"

#include "eos_api_trace.h"

#include "eos_anticheatclient.h"
#include "eos_anticheatserver.h"
#include "eos_auth.h"
#include "eos_connect.h"
#include "eos_custominvites.h"
#include "eos_ecom.h"
#include "eos_friends.h"
#include "eos_integratedplatform.h"
#include "eos_kws.h"
#include "eos_lobby.h"
#include "eos_mods.h"
#include "eos_p2p.h"
#include "eos_playerdatastorage.h"
#include "eos_progressionsnapshot.h"
#include "eos_reports.h"
#include "eos_rtc.h"
#include "eos_rtc_admin.h"
#include "eos_rtc_audio.h"
#include "eos_rtc_data.h"
#include "eos_sanctions.h"
#include "eos_sessions.h"
#include "eos_ui.h"
#include "eos_userinfo.h"

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_AddExternalIntegrityCatalog(EOS_HAntiCheatClient Handle, const EOS_AntiCheatClient_AddExternalIntegrityCatalogOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_AntiCheatClient_AddNotifyClientIntegrityViolated(EOS_HAntiCheatClient Handle, const EOS_AntiCheatClient_AddNotifyClientIntegrityViolatedOptions* Options, void* ClientData, EOS_AntiCheatClient_OnClientIntegrityViolatedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_AntiCheatClient_AddNotifyMessageToServer(EOS_HAntiCheatClient Handle, const EOS_AntiCheatClient_AddNotifyMessageToServerOptions* Options, void* ClientData, EOS_AntiCheatClient_OnMessageToServerCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_GetProtectMessageOutputLength(EOS_HAntiCheatClient Handle, const EOS_AntiCheatClient_GetProtectMessageOutputLengthOptions* Options, uint32_t* OutBufferSizeBytes)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutBufferSizeBytes;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_ProtectMessage(EOS_HAntiCheatClient Handle, const EOS_AntiCheatClient_ProtectMessageOptions* Options, void* OutBuffer, uint32_t* OutBytesWritten)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutBuffer;
    (void)OutBytesWritten;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_ReceiveMessageFromServer(EOS_HAntiCheatClient Handle, const EOS_AntiCheatClient_ReceiveMessageFromServerOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(void) EOS_AntiCheatClient_RemoveNotifyClientIntegrityViolated(EOS_HAntiCheatClient Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(void) EOS_AntiCheatClient_RemoveNotifyMessageToServer(EOS_HAntiCheatClient Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_Reserved01(EOS_HAntiCheatClient Handle, const EOS_AntiCheatClient_Reserved01Options* Options, int32_t* OutValue)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutValue;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_UnprotectMessage(EOS_HAntiCheatClient Handle, const EOS_AntiCheatClient_UnprotectMessageOptions* Options, void* OutBuffer, uint32_t* OutBytesWritten)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutBuffer;
    (void)OutBytesWritten;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_AntiCheatServer_AddNotifyClientActionRequired(EOS_HAntiCheatServer Handle, const EOS_AntiCheatServer_AddNotifyClientActionRequiredOptions* Options, void* ClientData, EOS_AntiCheatServer_OnClientActionRequiredCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_AntiCheatServer_AddNotifyClientAuthStatusChanged(EOS_HAntiCheatServer Handle, const EOS_AntiCheatServer_AddNotifyClientAuthStatusChangedOptions* Options, void* ClientData, EOS_AntiCheatServer_OnClientAuthStatusChangedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_AntiCheatServer_AddNotifyMessageToClient(EOS_HAntiCheatServer Handle, const EOS_AntiCheatServer_AddNotifyMessageToClientOptions* Options, void* ClientData, EOS_AntiCheatServer_OnMessageToClientCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_BeginSession(EOS_HAntiCheatServer Handle, const EOS_AntiCheatServer_BeginSessionOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_EndSession(EOS_HAntiCheatServer Handle, const EOS_AntiCheatServer_EndSessionOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_GetProtectMessageOutputLength(EOS_HAntiCheatServer Handle, const EOS_AntiCheatServer_GetProtectMessageOutputLengthOptions* Options, uint32_t* OutBufferSizeBytes)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutBufferSizeBytes;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_LogEvent(EOS_HAntiCheatServer Handle, const EOS_AntiCheatCommon_LogEventOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_LogGameRoundEnd(EOS_HAntiCheatServer Handle, const EOS_AntiCheatCommon_LogGameRoundEndOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_LogGameRoundStart(EOS_HAntiCheatServer Handle, const EOS_AntiCheatCommon_LogGameRoundStartOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_LogPlayerDespawn(EOS_HAntiCheatServer Handle, const EOS_AntiCheatCommon_LogPlayerDespawnOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_LogPlayerRevive(EOS_HAntiCheatServer Handle, const EOS_AntiCheatCommon_LogPlayerReviveOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_LogPlayerSpawn(EOS_HAntiCheatServer Handle, const EOS_AntiCheatCommon_LogPlayerSpawnOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_LogPlayerTakeDamage(EOS_HAntiCheatServer Handle, const EOS_AntiCheatCommon_LogPlayerTakeDamageOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_LogPlayerTick(EOS_HAntiCheatServer Handle, const EOS_AntiCheatCommon_LogPlayerTickOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_LogPlayerUseAbility(EOS_HAntiCheatServer Handle, const EOS_AntiCheatCommon_LogPlayerUseAbilityOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_LogPlayerUseWeapon(EOS_HAntiCheatServer Handle, const EOS_AntiCheatCommon_LogPlayerUseWeaponOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_ProtectMessage(EOS_HAntiCheatServer Handle, const EOS_AntiCheatServer_ProtectMessageOptions* Options, void* OutBuffer, uint32_t* OutBytesWritten)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutBuffer;
    (void)OutBytesWritten;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_ReceiveMessageFromClient(EOS_HAntiCheatServer Handle, const EOS_AntiCheatServer_ReceiveMessageFromClientOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_RegisterClient(EOS_HAntiCheatServer Handle, const EOS_AntiCheatServer_RegisterClientOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_RegisterEvent(EOS_HAntiCheatServer Handle, const EOS_AntiCheatCommon_RegisterEventOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(void) EOS_AntiCheatServer_RemoveNotifyClientActionRequired(EOS_HAntiCheatServer Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(void) EOS_AntiCheatServer_RemoveNotifyClientAuthStatusChanged(EOS_HAntiCheatServer Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(void) EOS_AntiCheatServer_RemoveNotifyMessageToClient(EOS_HAntiCheatServer Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_SetClientDetails(EOS_HAntiCheatServer Handle, const EOS_AntiCheatCommon_SetClientDetailsOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_SetClientNetworkState(EOS_HAntiCheatServer Handle, const EOS_AntiCheatServer_SetClientNetworkStateOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_SetGameSessionId(EOS_HAntiCheatServer Handle, const EOS_AntiCheatCommon_SetGameSessionIdOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_UnprotectMessage(EOS_HAntiCheatServer Handle, const EOS_AntiCheatServer_UnprotectMessageOptions* Options, void* OutBuffer, uint32_t* OutBytesWritten)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutBuffer;
    (void)OutBytesWritten;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatServer_UnregisterClient(EOS_HAntiCheatServer Handle, const EOS_AntiCheatServer_UnregisterClientOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EpicAccountId) EOS_Auth_GetMergedAccountByIndex(EOS_HAuth Handle, const EOS_EpicAccountId LocalUserId, const uint32_t Index)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)LocalUserId;
    (void)Index;
    return static_cast<EOS_EpicAccountId>(0);
}

EOS_DECLARE_FUNC(uint32_t) EOS_Auth_GetMergedAccountsCount(EOS_HAuth Handle, const EOS_EpicAccountId LocalUserId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)LocalUserId;
    return 0;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_Auth_GetSelectedAccountId(EOS_HAuth Handle, const EOS_EpicAccountId LocalUserId, EOS_EpicAccountId* OutSelectedAccountId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)LocalUserId;
    (void)OutSelectedAccountId;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(void) EOS_Auth_IdToken_Release(EOS_Auth_IdToken* IdToken)
{
    EOS_API_TRACE();
    (void)IdToken;}

EOS_DECLARE_FUNC(void) EOS_Auth_VerifyIdToken(EOS_HAuth Handle, const EOS_Auth_VerifyIdTokenOptions* Options, void* ClientData, const EOS_Auth_OnVerifyIdTokenCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_Connect_IdToken_Release(EOS_Connect_IdToken* IdToken)
{
    EOS_API_TRACE();
    (void)IdToken;}

EOS_DECLARE_FUNC(void) EOS_Connect_Logout(EOS_HConnect Handle, const EOS_Connect_LogoutOptions* Options, void* ClientData, const EOS_Connect_OnLogoutCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_Connect_VerifyIdToken(EOS_HConnect Handle, const EOS_Connect_VerifyIdTokenOptions* Options, void* ClientData, const EOS_Connect_OnVerifyIdTokenCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_CustomInvites_AcceptRequestToJoin(EOS_HCustomInvites Handle, const EOS_CustomInvites_AcceptRequestToJoinOptions* Options, void* ClientData, const EOS_CustomInvites_OnAcceptRequestToJoinCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_CustomInvites_AddNotifyCustomInviteAccepted(EOS_HCustomInvites Handle, const EOS_CustomInvites_AddNotifyCustomInviteAcceptedOptions* Options, void* ClientData, const EOS_CustomInvites_OnCustomInviteAcceptedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_CustomInvites_AddNotifyCustomInviteReceived(EOS_HCustomInvites Handle, const EOS_CustomInvites_AddNotifyCustomInviteReceivedOptions* Options, void* ClientData, const EOS_CustomInvites_OnCustomInviteReceivedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_CustomInvites_AddNotifyCustomInviteRejected(EOS_HCustomInvites Handle, const EOS_CustomInvites_AddNotifyCustomInviteRejectedOptions* Options, void* ClientData, const EOS_CustomInvites_OnCustomInviteRejectedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_CustomInvites_AddNotifyRequestToJoinAccepted(EOS_HCustomInvites Handle, const EOS_CustomInvites_AddNotifyRequestToJoinAcceptedOptions* Options, void* ClientData, const EOS_CustomInvites_OnRequestToJoinAcceptedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_CustomInvites_AddNotifyRequestToJoinReceived(EOS_HCustomInvites Handle, const EOS_CustomInvites_AddNotifyRequestToJoinReceivedOptions* Options, void* ClientData, const EOS_CustomInvites_OnRequestToJoinReceivedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_CustomInvites_AddNotifyRequestToJoinRejected(EOS_HCustomInvites Handle, const EOS_CustomInvites_AddNotifyRequestToJoinRejectedOptions* Options, void* ClientData, const EOS_CustomInvites_OnRequestToJoinRejectedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_CustomInvites_AddNotifyRequestToJoinResponseReceived(EOS_HCustomInvites Handle, const EOS_CustomInvites_AddNotifyRequestToJoinResponseReceivedOptions* Options, void* ClientData, const EOS_CustomInvites_OnRequestToJoinResponseReceivedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_CustomInvites_AddNotifySendCustomNativeInviteRequested(EOS_HCustomInvites Handle, const EOS_CustomInvites_AddNotifySendCustomNativeInviteRequestedOptions* Options, void* ClientData, const EOS_CustomInvites_OnSendCustomNativeInviteRequestedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_CustomInvites_FinalizeInvite(EOS_HCustomInvites Handle, const EOS_CustomInvites_FinalizeInviteOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(void) EOS_CustomInvites_RejectRequestToJoin(EOS_HCustomInvites Handle, const EOS_CustomInvites_RejectRequestToJoinOptions* Options, void* ClientData, const EOS_CustomInvites_OnRejectRequestToJoinCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_CustomInvites_RemoveNotifyCustomInviteAccepted(EOS_HCustomInvites Handle, EOS_NotificationId InId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)InId;}

EOS_DECLARE_FUNC(void) EOS_CustomInvites_RemoveNotifyCustomInviteReceived(EOS_HCustomInvites Handle, EOS_NotificationId InId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)InId;}

EOS_DECLARE_FUNC(void) EOS_CustomInvites_RemoveNotifyCustomInviteRejected(EOS_HCustomInvites Handle, EOS_NotificationId InId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)InId;}

EOS_DECLARE_FUNC(void) EOS_CustomInvites_RemoveNotifyRequestToJoinAccepted(EOS_HCustomInvites Handle, EOS_NotificationId InId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)InId;}

EOS_DECLARE_FUNC(void) EOS_CustomInvites_RemoveNotifyRequestToJoinReceived(EOS_HCustomInvites Handle, EOS_NotificationId InId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)InId;}

EOS_DECLARE_FUNC(void) EOS_CustomInvites_RemoveNotifyRequestToJoinRejected(EOS_HCustomInvites Handle, EOS_NotificationId InId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)InId;}

EOS_DECLARE_FUNC(void) EOS_CustomInvites_RemoveNotifyRequestToJoinResponseReceived(EOS_HCustomInvites Handle, EOS_NotificationId InId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)InId;}

EOS_DECLARE_FUNC(void) EOS_CustomInvites_RemoveNotifySendCustomNativeInviteRequested(EOS_HCustomInvites Handle, EOS_NotificationId InId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)InId;}

EOS_DECLARE_FUNC(void) EOS_CustomInvites_SendCustomInvite(EOS_HCustomInvites Handle, const EOS_CustomInvites_SendCustomInviteOptions* Options, void* ClientData, const EOS_CustomInvites_OnSendCustomInviteCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_CustomInvites_SendRequestToJoin(EOS_HCustomInvites Handle, const EOS_CustomInvites_SendRequestToJoinOptions* Options, void* ClientData, const EOS_CustomInvites_OnSendRequestToJoinCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_CustomInvites_SetCustomInvite(EOS_HCustomInvites Handle, const EOS_CustomInvites_SetCustomInviteOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_Ecom_CopyLastRedeemedEntitlementByIndex(EOS_HEcom Handle, const EOS_Ecom_CopyLastRedeemedEntitlementByIndexOptions* Options, char* OutRedeemedEntitlementId, int32_t* InOutRedeemedEntitlementIdLength)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutRedeemedEntitlementId;
    (void)InOutRedeemedEntitlementIdLength;
    return EOS_EResult::EOS_NotImplemented;
}

EOS_DECLARE_FUNC(uint32_t) EOS_Ecom_GetLastRedeemedEntitlementsCount(EOS_HEcom Handle, const EOS_Ecom_GetLastRedeemedEntitlementsCountOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return 0;
}

EOS_DECLARE_FUNC(void) EOS_Ecom_QueryEntitlementToken(EOS_HEcom Handle, const EOS_Ecom_QueryEntitlementTokenOptions* Options, void* ClientData, const EOS_Ecom_OnQueryEntitlementTokenCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_Ecom_QueryOwnershipBySandboxIds(EOS_HEcom Handle, const EOS_Ecom_QueryOwnershipBySandboxIdsOptions* Options, void* ClientData, const EOS_Ecom_OnQueryOwnershipBySandboxIdsCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(const char*) EOS_ENetworkStatus_ToString(EOS_ENetworkStatus NetworkStatus)
{
    EOS_API_TRACE();
    (void)NetworkStatus;
    return nullptr;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_Friends_AddNotifyBlockedUsersUpdate(EOS_HFriends Handle, const EOS_Friends_AddNotifyBlockedUsersUpdateOptions* Options, void* ClientData, const EOS_Friends_OnBlockedUsersUpdateCallback BlockedUsersUpdateHandler)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)BlockedUsersUpdateHandler;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_EpicAccountId) EOS_Friends_GetBlockedUserAtIndex(EOS_HFriends Handle, const EOS_Friends_GetBlockedUserAtIndexOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return static_cast<EOS_EpicAccountId>(0);
}

EOS_DECLARE_FUNC(int32_t) EOS_Friends_GetBlockedUsersCount(EOS_HFriends Handle, const EOS_Friends_GetBlockedUsersCountOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return 0;
}

EOS_DECLARE_FUNC(void) EOS_Friends_RemoveNotifyBlockedUsersUpdate(EOS_HFriends Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_KWS_AddNotifyPermissionsUpdateReceived(EOS_HKWS Handle, const EOS_KWS_AddNotifyPermissionsUpdateReceivedOptions* Options, void* ClientData, const EOS_KWS_OnPermissionsUpdateReceivedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_KWS_CopyPermissionByIndex(EOS_HKWS Handle, const EOS_KWS_CopyPermissionByIndexOptions* Options, EOS_KWS_PermissionStatus ** OutPermission)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutPermission;
    return EOS_EResult::EOS_NotImplemented;
}

EOS_DECLARE_FUNC(void) EOS_KWS_CreateUser(EOS_HKWS Handle, const EOS_KWS_CreateUserOptions* Options, void* ClientData, const EOS_KWS_OnCreateUserCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_KWS_GetPermissionByKey(EOS_HKWS Handle, const EOS_KWS_GetPermissionByKeyOptions* Options, EOS_EKWSPermissionStatus* OutPermission)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutPermission;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(int32_t) EOS_KWS_GetPermissionsCount(EOS_HKWS Handle, const EOS_KWS_GetPermissionsCountOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return 0;
}

EOS_DECLARE_FUNC(void) EOS_KWS_PermissionStatus_Release(EOS_KWS_PermissionStatus* PermissionStatus)
{
    EOS_API_TRACE();
    (void)PermissionStatus;}

EOS_DECLARE_FUNC(void) EOS_KWS_QueryAgeGate(EOS_HKWS Handle, const EOS_KWS_QueryAgeGateOptions* Options, void* ClientData, const EOS_KWS_OnQueryAgeGateCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_KWS_QueryPermissions(EOS_HKWS Handle, const EOS_KWS_QueryPermissionsOptions* Options, void* ClientData, const EOS_KWS_OnQueryPermissionsCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_KWS_RemoveNotifyPermissionsUpdateReceived(EOS_HKWS Handle, EOS_NotificationId InId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)InId;}

EOS_DECLARE_FUNC(void) EOS_KWS_RequestPermissions(EOS_HKWS Handle, const EOS_KWS_RequestPermissionsOptions* Options, void* ClientData, const EOS_KWS_OnRequestPermissionsCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_KWS_UpdateParentEmail(EOS_HKWS Handle, const EOS_KWS_UpdateParentEmailOptions* Options, void* ClientData, const EOS_KWS_OnUpdateParentEmailCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_Lobby_AddNotifyLeaveLobbyRequested(EOS_HLobby Handle, const EOS_Lobby_AddNotifyLeaveLobbyRequestedOptions* Options, void* ClientData, const EOS_Lobby_OnLeaveLobbyRequestedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_Lobby_AddNotifyLobbyInviteRejected(EOS_HLobby Handle, const EOS_Lobby_AddNotifyLobbyInviteRejectedOptions* Options, void* ClientData, const EOS_Lobby_OnLobbyInviteRejectedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_Lobby_AddNotifySendLobbyNativeInviteRequested(EOS_HLobby Handle, const EOS_Lobby_AddNotifySendLobbyNativeInviteRequestedOptions* Options, void* ClientData, const EOS_Lobby_OnSendLobbyNativeInviteRequestedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_Lobby_GetConnectString(EOS_HLobby Handle, const EOS_Lobby_GetConnectStringOptions* Options, char* OutBuffer, uint32_t* InOutBufferLength)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutBuffer;
    (void)InOutBufferLength;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(void) EOS_Lobby_HardMuteMember(EOS_HLobby Handle, const EOS_Lobby_HardMuteMemberOptions* Options, void* ClientData, const EOS_Lobby_OnHardMuteMemberCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_Lobby_ParseConnectString(EOS_HLobby Handle, const EOS_Lobby_ParseConnectStringOptions* Options, char* OutBuffer, uint32_t* InOutBufferLength)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutBuffer;
    (void)InOutBufferLength;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(void) EOS_Lobby_RemoveNotifyLeaveLobbyRequested(EOS_HLobby Handle, EOS_NotificationId InId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)InId;}

EOS_DECLARE_FUNC(void) EOS_Lobby_RemoveNotifyLobbyInviteRejected(EOS_HLobby Handle, EOS_NotificationId InId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)InId;}

EOS_DECLARE_FUNC(void) EOS_Lobby_RemoveNotifySendLobbyNativeInviteRequested(EOS_HLobby Handle, EOS_NotificationId InId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)InId;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_LobbyDetails_CopyMemberInfo(EOS_HLobbyDetails Handle, const EOS_LobbyDetails_CopyMemberInfoOptions* Options, EOS_LobbyDetails_MemberInfo ** OutLobbyDetailsMemberInfo)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutLobbyDetailsMemberInfo;
    return EOS_EResult::EOS_NotImplemented;
}

EOS_DECLARE_FUNC(void) EOS_LobbyDetails_MemberInfo_Release(EOS_LobbyDetails_MemberInfo* LobbyDetailsMemberInfo)
{
    EOS_API_TRACE();
    (void)LobbyDetailsMemberInfo;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_LobbyModification_SetAllowedPlatformIds(EOS_HLobbyModification Handle, const EOS_LobbyModification_SetAllowedPlatformIdsOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_Mods_CopyModInfo(EOS_HMods Handle, const EOS_Mods_CopyModInfoOptions* Options, EOS_Mods_ModInfo ** OutEnumeratedMods)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutEnumeratedMods;
    return EOS_EResult::EOS_NotImplemented;
}

EOS_DECLARE_FUNC(void) EOS_Mods_EnumerateMods(EOS_HMods Handle, const EOS_Mods_EnumerateModsOptions* Options, void* ClientData, const EOS_Mods_OnEnumerateModsCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_Mods_InstallMod(EOS_HMods Handle, const EOS_Mods_InstallModOptions* Options, void* ClientData, const EOS_Mods_OnInstallModCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_Mods_ModInfo_Release(EOS_Mods_ModInfo* ModInfo)
{
    EOS_API_TRACE();
    (void)ModInfo;}

EOS_DECLARE_FUNC(void) EOS_Mods_UninstallMod(EOS_HMods Handle, const EOS_Mods_UninstallModOptions* Options, void* ClientData, const EOS_Mods_OnUninstallModCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_Mods_UpdateMod(EOS_HMods Handle, const EOS_Mods_UpdateModOptions* Options, void* ClientData, const EOS_Mods_OnUpdateModCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_P2P_AddNotifyIncomingPacketQueueFull(EOS_HP2P Handle, const EOS_P2P_AddNotifyIncomingPacketQueueFullOptions* Options, void* ClientData, EOS_P2P_OnIncomingPacketQueueFullCallback IncomingPacketQueueFullHandler)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)IncomingPacketQueueFullHandler;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_P2P_ClearPacketQueue(EOS_HP2P Handle, const EOS_P2P_ClearPacketQueueOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_P2P_GetPacketQueueInfo(EOS_HP2P Handle, const EOS_P2P_GetPacketQueueInfoOptions* Options, EOS_P2P_PacketQueueInfo* OutPacketQueueInfo)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutPacketQueueInfo;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(void) EOS_P2P_RemoveNotifyIncomingPacketQueueFull(EOS_HP2P Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_P2P_SetPacketQueueSize(EOS_HP2P Handle, const EOS_P2P_SetPacketQueueSizeOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_PlayerDataStorage_DeleteCache(EOS_HPlayerDataStorage Handle, const EOS_PlayerDataStorage_DeleteCacheOptions* Options, void* ClientData, const EOS_PlayerDataStorage_OnDeleteCacheCompleteCallback CompletionCallback)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionCallback;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_ProgressionSnapshot_AddProgression(EOS_HProgressionSnapshot Handle, const EOS_ProgressionSnapshot_AddProgressionOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_ProgressionSnapshot_BeginSnapshot(EOS_HProgressionSnapshot Handle, const EOS_ProgressionSnapshot_BeginSnapshotOptions* Options, uint32_t* OutSnapshotId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutSnapshotId;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(void) EOS_ProgressionSnapshot_DeleteSnapshot(EOS_HProgressionSnapshot Handle, const EOS_ProgressionSnapshot_DeleteSnapshotOptions* Options, void* ClientData, const EOS_ProgressionSnapshot_OnDeleteSnapshotCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_ProgressionSnapshot_EndSnapshot(EOS_HProgressionSnapshot Handle, const EOS_ProgressionSnapshot_EndSnapshotOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(void) EOS_ProgressionSnapshot_SubmitSnapshot(EOS_HProgressionSnapshot Handle, const EOS_ProgressionSnapshot_SubmitSnapshotOptions* Options, void* ClientData, const EOS_ProgressionSnapshot_OnSubmitSnapshotCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_Reports_SendPlayerBehaviorReport(EOS_HReports Handle, const EOS_Reports_SendPlayerBehaviorReportOptions* Options, void* ClientData, const EOS_Reports_OnSendPlayerBehaviorReportCompleteCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_RTC_AddNotifyDisconnected(EOS_HRTC Handle, const EOS_RTC_AddNotifyDisconnectedOptions* Options, void* ClientData, const EOS_RTC_OnDisconnectedCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_RTC_AddNotifyParticipantStatusChanged(EOS_HRTC Handle, const EOS_RTC_AddNotifyParticipantStatusChangedOptions* Options, void* ClientData, const EOS_RTC_OnParticipantStatusChangedCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_RTC_AddNotifyRoomStatisticsUpdated(EOS_HRTC Handle, const EOS_RTC_AddNotifyRoomStatisticsUpdatedOptions* Options, void* ClientData, const EOS_RTC_OnRoomStatisticsUpdatedCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(void) EOS_RTC_BlockParticipant(EOS_HRTC Handle, const EOS_RTC_BlockParticipantOptions* Options, void* ClientData, const EOS_RTC_OnBlockParticipantCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(EOS_HRTCData) EOS_RTC_GetDataInterface(EOS_HRTC Handle)
{
    EOS_API_TRACE();
    (void)Handle;
    return static_cast<EOS_HRTCData>(0);
}

EOS_DECLARE_FUNC(void) EOS_RTC_RemoveNotifyDisconnected(EOS_HRTC Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(void) EOS_RTC_RemoveNotifyParticipantStatusChanged(EOS_HRTC Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(void) EOS_RTC_RemoveNotifyRoomStatisticsUpdated(EOS_HRTC Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_RTC_SetRoomSetting(EOS_HRTC Handle, const EOS_RTC_SetRoomSettingOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_RTC_SetSetting(EOS_HRTC Handle, const EOS_RTC_SetSettingOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(void) EOS_RTCAdmin_Kick(EOS_HRTCAdmin Handle, const EOS_RTCAdmin_KickOptions* Options, void* ClientData, const EOS_RTCAdmin_OnKickCompleteCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_RTCAdmin_SetParticipantHardMute(EOS_HRTCAdmin Handle, const EOS_RTCAdmin_SetParticipantHardMuteOptions* Options, void* ClientData, const EOS_RTCAdmin_OnSetParticipantHardMuteCompleteCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_RTCAudio_AddNotifyAudioBeforeRender(EOS_HRTCAudio Handle, const EOS_RTCAudio_AddNotifyAudioBeforeRenderOptions* Options, void* ClientData, const EOS_RTCAudio_OnAudioBeforeRenderCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_RTCAudio_AddNotifyAudioBeforeSend(EOS_HRTCAudio Handle, const EOS_RTCAudio_AddNotifyAudioBeforeSendOptions* Options, void* ClientData, const EOS_RTCAudio_OnAudioBeforeSendCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_RTCAudio_AddNotifyAudioDevicesChanged(EOS_HRTCAudio Handle, const EOS_RTCAudio_AddNotifyAudioDevicesChangedOptions* Options, void* ClientData, const EOS_RTCAudio_OnAudioDevicesChangedCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_RTCAudio_AddNotifyAudioInputState(EOS_HRTCAudio Handle, const EOS_RTCAudio_AddNotifyAudioInputStateOptions* Options, void* ClientData, const EOS_RTCAudio_OnAudioInputStateCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_RTCAudio_AddNotifyAudioOutputState(EOS_HRTCAudio Handle, const EOS_RTCAudio_AddNotifyAudioOutputStateOptions* Options, void* ClientData, const EOS_RTCAudio_OnAudioOutputStateCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_RTCAudio_AddNotifyParticipantUpdated(EOS_HRTCAudio Handle, const EOS_RTCAudio_AddNotifyParticipantUpdatedOptions* Options, void* ClientData, const EOS_RTCAudio_OnParticipantUpdatedCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_RTCAudio_CopyInputDeviceInformationByIndex(EOS_HRTCAudio Handle, const EOS_RTCAudio_CopyInputDeviceInformationByIndexOptions* Options, EOS_RTCAudio_InputDeviceInformation ** OutInputDeviceInformation)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutInputDeviceInformation;
    return EOS_EResult::EOS_NotImplemented;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_RTCAudio_CopyOutputDeviceInformationByIndex(EOS_HRTCAudio Handle, const EOS_RTCAudio_CopyOutputDeviceInformationByIndexOptions* Options, EOS_RTCAudio_OutputDeviceInformation ** OutOutputDeviceInformation)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutOutputDeviceInformation;
    return EOS_EResult::EOS_NotImplemented;
}

EOS_DECLARE_FUNC(const EOS_RTCAudio_AudioInputDeviceInfo *) EOS_RTCAudio_GetAudioInputDeviceByIndex(EOS_HRTCAudio Handle, const EOS_RTCAudio_GetAudioInputDeviceByIndexOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return nullptr;
}

EOS_DECLARE_FUNC(uint32_t) EOS_RTCAudio_GetAudioInputDevicesCount(EOS_HRTCAudio Handle, const EOS_RTCAudio_GetAudioInputDevicesCountOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return 0;
}

EOS_DECLARE_FUNC(const EOS_RTCAudio_AudioOutputDeviceInfo *) EOS_RTCAudio_GetAudioOutputDeviceByIndex(EOS_HRTCAudio Handle, const EOS_RTCAudio_GetAudioOutputDeviceByIndexOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return nullptr;
}

EOS_DECLARE_FUNC(uint32_t) EOS_RTCAudio_GetAudioOutputDevicesCount(EOS_HRTCAudio Handle, const EOS_RTCAudio_GetAudioOutputDevicesCountOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return 0;
}

EOS_DECLARE_FUNC(uint32_t) EOS_RTCAudio_GetInputDevicesCount(EOS_HRTCAudio Handle, const EOS_RTCAudio_GetInputDevicesCountOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return 0;
}

EOS_DECLARE_FUNC(uint32_t) EOS_RTCAudio_GetOutputDevicesCount(EOS_HRTCAudio Handle, const EOS_RTCAudio_GetOutputDevicesCountOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return 0;
}

EOS_DECLARE_FUNC(void) EOS_RTCAudio_InputDeviceInformation_Release(EOS_RTCAudio_InputDeviceInformation* DeviceInformation)
{
    EOS_API_TRACE();
    (void)DeviceInformation;}

EOS_DECLARE_FUNC(void) EOS_RTCAudio_OutputDeviceInformation_Release(EOS_RTCAudio_OutputDeviceInformation* DeviceInformation)
{
    EOS_API_TRACE();
    (void)DeviceInformation;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_RTCAudio_RegisterPlatformAudioUser(EOS_HRTCAudio Handle, const EOS_RTCAudio_RegisterPlatformAudioUserOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(void) EOS_RTCAudio_RemoveNotifyAudioBeforeRender(EOS_HRTCAudio Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(void) EOS_RTCAudio_RemoveNotifyAudioBeforeSend(EOS_HRTCAudio Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(void) EOS_RTCAudio_RemoveNotifyAudioDevicesChanged(EOS_HRTCAudio Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(void) EOS_RTCAudio_RemoveNotifyAudioInputState(EOS_HRTCAudio Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(void) EOS_RTCAudio_RemoveNotifyAudioOutputState(EOS_HRTCAudio Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(void) EOS_RTCAudio_RemoveNotifyParticipantUpdated(EOS_HRTCAudio Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_RTCAudio_SendAudio(EOS_HRTCAudio Handle, const EOS_RTCAudio_SendAudioOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_RTCAudio_SetAudioInputSettings(EOS_HRTCAudio Handle, const EOS_RTCAudio_SetAudioInputSettingsOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_RTCAudio_SetAudioOutputSettings(EOS_HRTCAudio Handle, const EOS_RTCAudio_SetAudioOutputSettingsOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_RTCAudio_UnregisterPlatformAudioUser(EOS_HRTCAudio Handle, const EOS_RTCAudio_UnregisterPlatformAudioUserOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(void) EOS_RTCAudio_UnregisterPlatformUser(EOS_HRTCAudio Handle, const EOS_RTCAudio_UnregisterPlatformUserOptions* Options, void* ClientData, const EOS_RTCAudio_OnUnregisterPlatformUserCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_RTCAudio_UpdateParticipantVolume(EOS_HRTCAudio Handle, const EOS_RTCAudio_UpdateParticipantVolumeOptions* Options, void* ClientData, const EOS_RTCAudio_OnUpdateParticipantVolumeCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_RTCData_AddNotifyDataReceived(EOS_HRTCData Handle, const EOS_RTCData_AddNotifyDataReceivedOptions* Options, void* ClientData, const EOS_RTCData_OnDataReceivedCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_RTCData_AddNotifyParticipantUpdated(EOS_HRTCData Handle, const EOS_RTCData_AddNotifyParticipantUpdatedOptions* Options, void* ClientData, const EOS_RTCData_OnParticipantUpdatedCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(void) EOS_RTCData_RemoveNotifyDataReceived(EOS_HRTCData Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(void) EOS_RTCData_RemoveNotifyParticipantUpdated(EOS_HRTCData Handle, EOS_NotificationId NotificationId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)NotificationId;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_RTCData_SendData(EOS_HRTCData Handle, const EOS_RTCData_SendDataOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(void) EOS_RTCData_UpdateReceiving(EOS_HRTCData Handle, const EOS_RTCData_UpdateReceivingOptions* Options, void* ClientData, const EOS_RTCData_OnUpdateReceivingCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_RTCData_UpdateSending(EOS_HRTCData Handle, const EOS_RTCData_UpdateSendingOptions* Options, void* ClientData, const EOS_RTCData_OnUpdateSendingCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_Sanctions_CopyPlayerSanctionByIndex(EOS_HSanctions Handle, const EOS_Sanctions_CopyPlayerSanctionByIndexOptions* Options, EOS_Sanctions_PlayerSanction ** OutSanction)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)OutSanction;
    return EOS_EResult::EOS_NotImplemented;
}

EOS_DECLARE_FUNC(void) EOS_Sanctions_CreatePlayerSanctionAppeal(EOS_HSanctions Handle, const EOS_Sanctions_CreatePlayerSanctionAppealOptions* Options, void* ClientData, const EOS_Sanctions_CreatePlayerSanctionAppealCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(uint32_t) EOS_Sanctions_GetPlayerSanctionCount(EOS_HSanctions Handle, const EOS_Sanctions_GetPlayerSanctionCountOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return 0;
}

EOS_DECLARE_FUNC(void) EOS_Sanctions_PlayerSanction_Release(EOS_Sanctions_PlayerSanction* Sanction)
{
    EOS_API_TRACE();
    (void)Sanction;}

EOS_DECLARE_FUNC(void) EOS_Sanctions_QueryActivePlayerSanctions(EOS_HSanctions Handle, const EOS_Sanctions_QueryActivePlayerSanctionsOptions* Options, void* ClientData, const EOS_Sanctions_OnQueryActivePlayerSanctionsCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_SessionModification_SetAllowedPlatformIds(EOS_HSessionModification Handle, const EOS_SessionModification_SetAllowedPlatformIdsOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_Sessions_AddNotifyLeaveSessionRequested(EOS_HSessions Handle, const EOS_Sessions_AddNotifyLeaveSessionRequestedOptions* Options, void* ClientData, const EOS_Sessions_OnLeaveSessionRequestedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_Sessions_AddNotifySendSessionNativeInviteRequested(EOS_HSessions Handle, const EOS_Sessions_AddNotifySendSessionNativeInviteRequestedOptions* Options, void* ClientData, const EOS_Sessions_OnSendSessionNativeInviteRequestedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_Sessions_AddNotifySessionInviteRejected(EOS_HSessions Handle, const EOS_Sessions_AddNotifySessionInviteRejectedOptions* Options, void* ClientData, const EOS_Sessions_OnSessionInviteRejectedCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(void) EOS_Sessions_RemoveNotifyLeaveSessionRequested(EOS_HSessions Handle, EOS_NotificationId InId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)InId;}

EOS_DECLARE_FUNC(void) EOS_Sessions_RemoveNotifySendSessionNativeInviteRequested(EOS_HSessions Handle, EOS_NotificationId InId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)InId;}

EOS_DECLARE_FUNC(void) EOS_Sessions_RemoveNotifySessionInviteRejected(EOS_HSessions Handle, EOS_NotificationId InId)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)InId;}

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_UI_AddNotifyMemoryMonitor(EOS_HUI Handle, const EOS_UI_AddNotifyMemoryMonitorOptions* Options, void* ClientData, const EOS_UI_OnMemoryMonitorCallback NotificationFn)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)NotificationFn;
    return EOS_INVALID_NOTIFICATIONID;
}

EOS_DECLARE_FUNC(EOS_Bool) EOS_UI_GetFriendsExclusiveInput(EOS_HUI Handle, const EOS_UI_GetFriendsExclusiveInputOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_FALSE;
}

EOS_DECLARE_FUNC(EOS_UI_EInputStateButtonFlags) EOS_UI_GetToggleFriendsButton(EOS_HUI Handle, const EOS_UI_GetToggleFriendsButtonOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return static_cast<EOS_UI_EInputStateButtonFlags>(0);
}

EOS_DECLARE_FUNC(EOS_Bool) EOS_UI_IsSocialOverlayPaused(EOS_HUI Handle, const EOS_UI_IsSocialOverlayPausedOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_FALSE;
}

EOS_DECLARE_FUNC(EOS_Bool) EOS_UI_IsValidButtonCombination(EOS_HUI Handle, EOS_UI_EInputStateButtonFlags ButtonCombination)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)ButtonCombination;
    return EOS_FALSE;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_UI_PauseSocialOverlay(EOS_HUI Handle, const EOS_UI_PauseSocialOverlayOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_UI_PrePresent(EOS_HUI Handle, const EOS_UI_PrePresentOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(void) EOS_UI_RemoveNotifyMemoryMonitor(EOS_HUI Handle, EOS_NotificationId Id)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Id;}

EOS_DECLARE_FUNC(EOS_EResult) EOS_UI_ReportInputState(EOS_HUI Handle, const EOS_UI_ReportInputStateOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(EOS_EResult) EOS_UI_SetToggleFriendsButton(EOS_HUI Handle, const EOS_UI_SetToggleFriendsButtonOptions* Options)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    return EOS_EResult::EOS_Success;
}

EOS_DECLARE_FUNC(void) EOS_UI_ShowBlockPlayer(EOS_HUI Handle, const EOS_UI_ShowBlockPlayerOptions* Options, void* ClientData, const EOS_UI_OnShowBlockPlayerCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_UI_ShowNativeProfile(EOS_HUI Handle, const EOS_UI_ShowNativeProfileOptions* Options, void* ClientData, const EOS_UI_OnShowNativeProfileCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}

EOS_DECLARE_FUNC(void) EOS_UI_ShowReportPlayer(EOS_HUI Handle, const EOS_UI_ShowReportPlayerOptions* Options, void* ClientData, const EOS_UI_OnShowReportPlayerCallback CompletionDelegate)
{
    EOS_API_TRACE();
    (void)Handle;
    (void)Options;
    (void)ClientData;
    (void)CompletionDelegate;}
